In [125]:
!pip3 install pandas fuzzywuzzy
!pip3 install matplotlib
!pip3 install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/lonewolf/Library/Python/3.9/lib/python/site-packages (2.3.0)
Requirement already satisfied: fuzzywuzzy in /Users/lonewolf/Library/Python/3.9/lib/python/site-packages (0.18.0)
Requirement already satisfied: numpy>=1.22.4 in /Users/lonewolf/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/lonewolf/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.2)
Requirement already satisfied: pytz>=2020.1 in /Users/lonewolf/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/lonewolf/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
WARNING: You are using pip version 21.2.4; however, version 25.1.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in /Users/lonewolf/Library/Python/3.9/lib/python/site-packages (3.9.4)
Requirement already satisfied: pillow>=8 in /Users/lonewolf/Library/Python/3.9/lib/python/site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: packaging>=20.0 in /Users/lonewolf/Library/Python/3.9/lib/python/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/lonewolf/Library/Python/3.9/lib/python/site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /Users/lonewolf/Library/Python/3.9/lib/python/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: fonttools>=4.22.0 in /Users/lonewolf/Library/Python/3.9/lib/python/site-packages (from matplotlib) (4.58.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/lonewolf/Library/Python/3.9/lib/python/site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: importlib-resources>=3.2.0 in /Users/lonewolf/Library/Python/3.9/lib/python/site-packages (from matplotlib) (6.5.2)
Requirement already satisfied: numpy>=1.23 in /Users/lonewolf/Library/Python/3.9/lib/python/site-packages (from matplotlib) (2.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /Users/lonewolf/Library/Python/3.9/lib/python/site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /Users/lonewolf/Library/Python/3.9/lib/python/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: zipp>=3.1.0 in /Users/lonewolf/Library/Python/3.9/lib/python/site-packages (from importlib-resources>=3.2.0->matplotlib) (3.23.0)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib) (1.15.0)
WARNING: You are using pip version 21.2.4; however, version 25.1.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/lonewolf/Library/Python/3.9/lib/python/site-packages (2.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/lonewolf/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/lonewolf/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.2)
Requirement already satisfied: numpy>=1.22.4 in /Users/lonewolf/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/lonewolf/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
WARNING: You are using pip version 21.2.4; however, version 25.1.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [126]:
import pandas as pd
from fuzzywuzzy import fuzz
from datetime import datetime
import matplotlib.pyplot as plt
from dateutil import parser
import json

In [150]:
file = './goldens.csv'

golden = pd.read_csv(file).fillna("NA")
extraction = pd.read_csv('./extracted_results.csv').fillna("NA").replace('', 'NA').replace('None', 'NA')
# validation = pd.read_csv("./validation_results.csv")

columns_to_check = ['classification', 'Passport_Number', 'Passport_Type', 'Given_Name', 'Date_Of_Birth', 'Surname', 'Gender', 'Nationality', 'Issuing_Country','MRZ', 'Date_Of_Issue', 'Date_Of_Expiry', 'Place_Of_Birth', 'Issuing_Authority']

In [151]:
golden['key'] = golden['case_name'] + '_' + golden['filename']
extraction['key'] = extraction['case_name'] + '_' + extraction['filename']
# validation['key'] = validation['case_name'] + '_' + validation['filename']

In [152]:
golden = golden[golden['key'] != 'NA']

In [153]:
golden.tail()

,case_name,filename,classification,Passport_Number,Passport_Type,Given_Name,Date_Of_Birth,Surname,Gender,Nationality,Issuing_Country,MRZ,Date_Of_Issue,Date_Of_Expiry,Place_Of_Birth,Issuing_Authority,key
0,case_2,1.jpg,Passport,PQ689641,P,AMJAD,05/02/1988,HUSSAIN,M,PAKISTANI,PAK,P<PAKHUSSAIN<<AMJAD<<<<<<<<<<<<<<<<<<<<<<<<<PQ...,11/21/2009,11/20/2014,"ABBOTTABAD, PAK",PAKISTAN,case_2_1.jpg
1,case_2,2.jpg,Passport,B728204,P,AZEEM FOUZIA,03/01/1990,AZEEM,F,PAKISTANI,PAK,P<PAKAZEEM<<FOUZIA<<<<<<<<<<<<<<<<<<<<<<<<<<CS...,06/01/2012,05/31/2017,"DERA GHAZI KHAN, PAK",PAKISTAN,case_2_2.jpg
2,case_1,1.jpg,Passport,PQ689661,P,AMJAD,05/02/1988,HUSSAIN,M,PAKISTANI,PAK,P<PAKHUSSAIN<<AMJAD<<<<<<<<<<<<<<<<<<<<<<<<<PQ...,11/21/2009,11/20/2014,"ABBOTTABAD, PAK",PAKISTAN,case_1_1.jpg
3,case_1,2.jpg,Passport,B728204,P,AZEEM FOUZIA,03/01/1990,AZEEM,F,PAKISTANI,PAK,P<PAKAZEEM<<FOUZIA<<<<<<<<<<<<<<<<<<<<<<<<<<CS...,06/01/2012,05/31/2017,"DERA GHAZI KHAN, PAK",PAKISTAN,case_1_2.jpg

In [154]:
# validation.columns

In [155]:
# validations = validation[columns_to_check + ['key']]
# validations

In [156]:
import ast

def normalize_columns(value):
    k =  ast.literal_eval(value)
    # print(value, type(value), k)
    return k[0]

comparison = extraction[columns_to_check + ['key'] ].copy()

for column in columns_to_check:
    if extraction[column].dtype == 'string':
        comparison[column] = extraction[column].apply(normalize_columns).copy()

# df_copy['column_name'] = df_copy['column_name'].apply(lambda x: ast.literal_eval(x)[0] if isinstance(x, str) else x)
comparison = comparison.fillna("NA").replace('', 'NA').replace('None', 'NA')

In [157]:
pd.set_option('display.max_columns', None)
comparison.head()

,classification,Passport_Number,Passport_Type,Given_Name,Date_Of_Birth,Surname,Gender,Nationality,Issuing_Country,MRZ,Date_Of_Issue,Date_Of_Expiry,Place_Of_Birth,Issuing_Authority,key
0,Passport,PQ6896461,P,AMJAD,05/02/1988,HUSSAIN,M,PAKISTANI,PAK,P<PAKHUSSAIN<<AMJAD<<<<<<<<<<<<<<<<<<<<<<<<<PQ...,11/21/2009,11/20/2014,"ABBOTTABAD, PAK",PAKISTAN,case_2_1.jpg
1,Passport,B7282004,P,AZEEM FOUZIA,03/01/1990,AZEEM,F,PAKISTANI,PAK,P<PAKAZEEM<<FOUZIA<<<<<<<<<<<<<<<<<<<<<<<<<<CS...,06/01/2012,05/31/2017,"DERA GHAZI KHAN, PAK",PAKISTAN,case_2_2.jpg
2,Passport,PQ6896461,P,AMJAD,05/02/1988,HUSSAIN,M,PAKISTANI,PAK,P<PAKHUSSAIN<<AMJAD<<<<<<<<<<<<<<<<<<<<<<<<<PQ...,11/21/2009,11/20/2014,"ABBOTTABAD, PAK",PAKISTAN,case_1_1.jpg
3,Passport,B7282004,P,AZEEM FOUZIA,03/01/1990,AZEEM,F,PAKISTANI,PAK,P<PAKAZEEM<<FOUZIA<<<<<<<<<<<<<<<<<<<<<<<<<<CS...,06/01/2012,05/31/2017,"DERA GHAZI KHAN, PAK",PAKISTAN,case_1_2.jpg

In [158]:
comparison.tail()

,classification,Passport_Number,Passport_Type,Given_Name,Date_Of_Birth,Surname,Gender,Nationality,Issuing_Country,MRZ,Date_Of_Issue,Date_Of_Expiry,Place_Of_Birth,Issuing_Authority,key
0,Passport,PQ6896461,P,AMJAD,05/02/1988,HUSSAIN,M,PAKISTANI,PAK,P<PAKHUSSAIN<<AMJAD<<<<<<<<<<<<<<<<<<<<<<<<<PQ...,11/21/2009,11/20/2014,"ABBOTTABAD, PAK",PAKISTAN,case_2_1.jpg
1,Passport,B7282004,P,AZEEM FOUZIA,03/01/1990,AZEEM,F,PAKISTANI,PAK,P<PAKAZEEM<<FOUZIA<<<<<<<<<<<<<<<<<<<<<<<<<<CS...,06/01/2012,05/31/2017,"DERA GHAZI KHAN, PAK",PAKISTAN,case_2_2.jpg
2,Passport,PQ6896461,P,AMJAD,05/02/1988,HUSSAIN,M,PAKISTANI,PAK,P<PAKHUSSAIN<<AMJAD<<<<<<<<<<<<<<<<<<<<<<<<<PQ...,11/21/2009,11/20/2014,"ABBOTTABAD, PAK",PAKISTAN,case_1_1.jpg
3,Passport,B7282004,P,AZEEM FOUZIA,03/01/1990,AZEEM,F,PAKISTANI,PAK,P<PAKAZEEM<<FOUZIA<<<<<<<<<<<<<<<<<<<<<<<<<<CS...,06/01/2012,05/31/2017,"DERA GHAZI KHAN, PAK",PAKISTAN,case_1_2.jpg

In [159]:
# validations.head()

In [160]:
len(set(comparison['key']) - set(golden['key']))

0

In [161]:
len(set(golden['key']) - set(comparison['key']))

0

In [162]:
# len(set(validations['key']) - set(comparison['key']))

In [163]:
# set(validations['key']) - set(comparison['key'])

In [164]:
# set(comparison['key']) - set(validations['key'])

In [165]:
# if set(validations['key']) - set(comparison['key']) or set(comparison['key']) - set(validations['key']):
#     raise Exception("Validations and Comparisons datasets must not contain mismatching cases!")

In [166]:
set(golden['key']) - set(comparison['key'])

set()

In [167]:
def fuzzy_match(value1, value2):
    return fuzz.ratio(value1, value2)


def clean_str(val):
    symbols = ['£', ",", "'", '"', 'PS']
    val_copy = val
    
    for symbol in symbols:
        val_copy = val_copy.replace(symbol, "")
    
    return val_copy.strip()


def parse_kilo_to_val(value):
    
    return float( value.split('k')[0]) * 1000

In [168]:
def custom_callback(column_name, value1, value2):
    try:
        fuzzy_colnames = []
        date_colnames = []

        value2 = not value2.empty and value2.values[0] or 'NA'

        if 'na' in (value1, value2) or 'NA' in (value1, value2):
            if value1 == value2: 
                return True 
            
            return False 
        
        if column_name in fuzzy_colnames:
            if value1 is None:
                if value2 is None:
                    return True
                return False
            score = fuzzy_match(value1.lower(), value2.lower())
            return score > 80

        if column_name in date_colnames:
            try:
                first_match_try = datetime.strptime(value1.strip(), '%d/%m/%Y') == datetime.strptime(value2.strip(), '%d/%m/%Y')
                
                if not first_match_try:
                    return datetime.strptime(value1.strip(), '%m/%d/%Y') == datetime.strptime(value2.strip(), '%d/%m/%Y')
                
                return first_match_try
            except Exception as e:
                print("date err", column, value1, value2, value1 == value2, e)
                return value1 == value2

        try:
            return value1.lower().replace(" ", '') == value2.lower().replace(" ", '')
        except:
            return value1 == value2

    except:
        print(column_name, value1, type(value1), value2, type(value2))

In [172]:
def get_comparison_result(row, golden_df, column):
    # Find the matching row in golden
    match = golden_df[golden_df['key'] == row['key']]

    # Get the golden value (or None if not found)
    if not match.empty:
        golden_value = match.iloc[0][column]
    else:
        golden_value = None

    print(f"Comparing → comparison: {row[column]}  vs  golden: {golden_value}")
    
    # Call comparison function
    return custom_callback(column, row[column], golden_value)

# Create empty dataframe for results
result_data = {'key': []}
result_df = pd.DataFrame(result_data)

# Compare each column
for column in columns_to_check:
    result_df[column] = comparison.apply(get_comparison_result, args=(golden, column), axis=1)

# Add key column
result_df['key'] = comparison['key']

classification Passport <class 'str'> Passport <class 'str'>
classification Passport <class 'str'> Passport <class 'str'>
classification Passport <class 'str'> Passport <class 'str'>
classification Passport <class 'str'> Passport <class 'str'>
Passport_Number PQ6896461 <class 'str'> PQ689641 <class 'str'>
Passport_Number B7282004 <class 'str'> B728204 <class 'str'>
Passport_Number PQ6896461 <class 'str'> PQ689661 <class 'str'>
Passport_Number B7282004 <class 'str'> B728204 <class 'str'>
Passport_Type P <class 'str'> P <class 'str'>
Passport_Type P <class 'str'> P <class 'str'>
Passport_Type P <class 'str'> P <class 'str'>
Passport_Type P <class 'str'> P <class 'str'>
Given_Name AMJAD <class 'str'> AMJAD <class 'str'>
Given_Name AZEEM FOUZIA <class 'str'> AZEEM FOUZIA <class 'str'>
Given_Name AMJAD <class 'str'> AMJAD <class 'str'>
Given_Name AZEEM FOUZIA <class 'str'> AZEEM FOUZIA <class 'str'>
Date_Of_Birth 05/02/1988 <class 'str'> 05/02/1988 <class 'str'>
Date_Of_Birth 03/01/1990 <class 'str'> 03/01/1990 <class 'str'>
Date_Of_Birth 05/02/1988 <class 'str'> 05/02/1988 <class 'str'>
Date_Of_Birth 03/01/1990 <class 'str'> 03/01/1990 <class 'str'>
Surname HUSSAIN <class 'str'> HUSSAIN <class 'str'>
Surname AZEEM <class 'str'> AZEEM <class 'str'>
Surname HUSSAIN <class 'str'> HUSSAIN <class 'str'>
Surname AZEEM <class 'str'> AZEEM <class 'str'>
Gender M <class 'str'> M <class 'str'>
Gender F <class 'str'> F <class 'str'>
Gender M <class 'str'> M <class 'str'>
Gender F <class 'str'> F <class 'str'>
Nationality PAKISTANI <class 'str'> PAKISTANI <class 'str'>
Nationality PAKISTANI <class 'str'> PAKISTANI <class 'str'>
Nationality PAKISTANI <class 'str'> PAKISTANI <class 'str'>
Nationality PAKISTANI <class 'str'> PAKISTANI <class 'str'>
Issuing_Country PAK <class 'str'> PAK <class 'str'>
Issuing_Country PAK <class 'str'> PAK <class 'str'>
Issuing_Country PAK <class 'str'> PAK <class 'str'>
Issuing_Country PAK <class 'str'> PAK <class 'str'>
MRZ P<PAKHUSSAIN<<AMJAD<<<<<<<<<<<<<<<<<<<<<<<<<PQ68964615PAK8805027M14112031310109186465<90 <class 'str'> P<PAKHUSSAIN<<AMJAD<<<<<<<<<<<<<<<<<<<<<<<<<PQ68964615PAK8805027M14112031310109186465<90 <class 'str'>
MRZ P<PAKAZEEM<<FOUZIA<<<<<<<<<<<<<<<<<<<<<<<<<<CS18599828PAK9003015F17053133630279669982<42 <class 'str'> P<PAKAZEEM<<FOUZIA<<<<<<<<<<<<<<<<<<<<<<<<<<CS18599828PAK9003015F17053133630279669982<42 <class 'str'>
MRZ P<PAKHUSSAIN<<AMJAD<<<<<<<<<<<<<<<<<<<<<<<<<PQ68964615PAK8805027M14112031310109186465<90 <class 'str'> P<PAKHUSSAIN<<AMJAD<<<<<<<<<<<<<<<<<<<<<<<<<PQ68964615PAK8805027M14112031310109186465<90 <class 'str'>
MRZ P<PAKAZEEM<<FOUZIA<<<<<<<<<<<<<<<<<<<<<<<<<<CS18599828PAK9003015F17053133630279669982<42 <class 'str'> P<PAKAZEEM<<FOUZIA<<<<<<<<<<<<<<<<<<<<<<<<<<CS18599828PAK9003015F17053133630279669982<42 <class 'str'>
Date_Of_Issue 11/21/2009 <class 'str'> 11/21/2009 <class 'str'>
Date_Of_Issue 06/01/2012 <class 'str'> 06/01/2012 <class 'str'>
Date_Of_Issue 11/21/2009 <class 'str'> 11/21/2009 <class 'str'>
Date_Of_Issue 06/01/2012 <class 'str'> 06/01/2012 <class 'str'>
Date_Of_Expiry 11/20/2014 <class 'str'> 11/20/2014 <class 'str'>
Date_Of_Expiry 05/31/2017 <class 'str'> 05/31/2017 <class 'str'>
Date_Of_Expiry 11/20/2014 <class 'str'> 11/20/2014 <class 'str'>
Date_Of_Expiry 05/31/2017 <class 'str'> 05/31/2017 <class 'str'>
Place_Of_Birth ABBOTTABAD, PAK <class 'str'> ABBOTTABAD, PAK <class 'str'>
Place_Of_Birth DERA GHAZI KHAN, PAK <class 'str'> DERA GHAZI KHAN, PAK <class 'str'>
Place_Of_Birth ABBOTTABAD, PAK <class 'str'> ABBOTTABAD, PAK <class 'str'>
Place_Of_Birth DERA GHAZI KHAN, PAK <class 'str'> DERA GHAZI KHAN, PAK <class 'str'>
Issuing_Authority PAKISTAN <class 'str'> PAKISTAN <class 'str'>
Issuing_Authority PAKISTAN <class 'str'> PAKISTAN <class 'str'>
Issuing_Authority PAKISTAN <class 'str'> PAKISTAN <class 'str'>
Issuing_Authority PAKISTAN <class 'str'> PAKISTAN <class 'str'>

In [116]:
validated_df.head()

,key,classification,Passport_Number,Passport_Type,Given_Name,Date_Of_Birth,Surname,Gender,Nationality,Issuing_Country,MRZ,Date_Of_Issue,Date_Of_Expiry,Place_Of_Birth,Issuing_Authority
0,case_2_1.jpg,True,False,True,True,True,True,True,True,True,True,True,True,True,True
1,case_2_2.jpg,True,False,True,True,True,Fail,True,True,True,True,True,True,True,True
2,case_1_1.jpg,True,False,True,True,True,True,True,True,True,True,True,True,True,True
3,case_1_2.jpg,True,False,True,True,True,Fail,True,True,True,True,True,True,True,True

In [117]:
result_df.head()

,key,classification,Passport_Number,Passport_Type,Given_Name,Date_Of_Birth,Surname,Gender,Nationality,Issuing_Country,MRZ,Date_Of_Issue,Date_Of_Expiry,Place_Of_Birth,Issuing_Authority
0,case_2_1.jpg,True,False,True,True,True,True,True,True,True,True,True,True,True,True
1,case_2_2.jpg,True,False,True,True,True,True,True,True,True,True,True,True,True,True
2,case_1_1.jpg,True,False,True,True,True,True,True,True,True,True,True,True,True,True
3,case_1_2.jpg,True,False,True,True,True,True,True,True,True,True,True,True,True,True

In [118]:
def get_field_level_accuracy(target, fields=None):

    if not fields:
        fields = target.columns
    
    result = {}

    for field in fields:
        counts = target[field].value_counts()
        total_counts = counts.sum()
        true_fields = counts.get(True, 0)
        false_fields = counts.get(False, 0)

        result[field] = round(true_fields/total_counts, 3)
        print(field, "total", total_counts, "true", true_fields)

    return result


def get_total_field_accuracy(target, fields=None):

    if not fields:
        fields = target.columns
    
    total_eligible_fields = 0
    total_matches = 0

    for field in fields:
        counts = target[field].value_counts()
        total_eligible_fields += counts.sum()
        total_matches += counts.get(True, 0)

    return round(total_matches / total_eligible_fields, 3)


def get_validated_field_level_accuracy(target, fields=None):

    if not fields:
        fields = target.columns
    
    result = {}
    total = 0
    for field in fields:
        counts = target[field].value_counts()
        total_counts = counts.sum()
        true_fields = counts.get(True, 0) # Fields that passed validation and are accurate against the Goldens
        not_applicable_fields = counts.get("fail", 0) # Fields that failed Validation
        
        value = round(true_fields/(total_counts - not_applicable_fields), 3)
        result[field] = value
        total += value

    result['avg'] = round( total / len(fields) , 3 )
    return result


def get_field_automation_rate(target, fields=None):

    if not fields:
        fields = target.columns
    
    result = {}
    total = 0
    for field in fields:
        
        counts = target[field].value_counts()
        total_counts = counts.sum()
        true_fields = counts.get(True, 0) # Fields that passes validation
        false_fields = counts.get(False, 0) # Fields that passed validation but are incaccurate
        value = round((true_fields + false_fields)/total_counts, 3)
        result[field] = value
        total += value

    result['avg'] = round(total / len(fields), 3)
    return result


def get_false_positives(target, fields=None):
    
    if not fields:
        fields = target.columns
    
    result = {}
    total = 0
    for field in fields:
        counts = target[field].value_counts()
        total_counts = counts.sum()
        false_fields = counts.get(False, 0) # Fields that passed validation and are accurate against the Goldens
        # not_applicable_fields = counts.get("fail", 0) # Fields that failed Validation
        
        value = round(false_fields/total_counts , 5)
        result[field] = value
        total += value

    result['avg'] = round( total / len(fields) , 3 )
    return result

In [119]:
accuracy = {
    "total_FA": get_total_field_accuracy(result_df, columns_to_check),
    "FLA": get_field_level_accuracy(result_df, columns_to_check),
    
    "validated_FLA": get_validated_field_level_accuracy(validated_df, columns_to_check),
    "field_automation_rate": get_field_automation_rate(validated_df, columns_to_check),
    "False Positives": get_false_positives(validated_df, columns_to_check)
}

classification total 4 true 4
Passport_Number total 4 true 0
Passport_Type total 4 true 4
Given_Name total 4 true 4
Date_Of_Birth total 4 true 4
Surname total 4 true 4
Gender total 4 true 4
Nationality total 4 true 4
Issuing_Country total 4 true 4
MRZ total 4 true 4
Date_Of_Issue total 4 true 4
Date_Of_Expiry total 4 true 4
Place_Of_Birth total 4 true 4
Issuing_Authority total 4 true 4

In [124]:
pretty_printed_dict = json.dumps(accuracy, indent=5)
print(pretty_printed_dict)

{
     "total_FA": 0.929,
     "FLA": {
          "classification": 1.0,
          "Passport_Number": 0.0,
          "Passport_Type": 1.0,
          "Given_Name": 1.0,
          "Date_Of_Birth": 1.0,
          "Surname": 1.0,
          "Gender": 1.0,
          "Nationality": 1.0,
          "Issuing_Country": 1.0,
          "MRZ": 1.0,
          "Date_Of_Issue": 1.0,
          "Date_Of_Expiry": 1.0,
          "Place_Of_Birth": 1.0,
          "Issuing_Authority": 1.0
     },
     "validated_FLA": {
          "classification": 1.0,
          "Passport_Number": 0.0,
          "Passport_Type": 1.0,
          "Given_Name": 1.0,
          "Date_Of_Birth": 1.0,
          "Surname": 0.5,
          "Gender": 1.0,
          "Nationality": 1.0,
          "Issuing_Country": 1.0,
          "MRZ": 1.0,
          "Date_Of_Issue": 1.0,
          "Date_Of_Expiry": 1.0,
          "Place_Of_Birth": 1.0,
          "Issuing_Authority": 1.0,
          "avg": 0.893
     },
     "field_automation_rate": {
          "classification": 1.0,
          "Passport_Number": 1.0,
          "Passport_Type": 1.0,
          "Given_Name": 1.0,
          "Date_Of_Birth": 1.0,
          "Surname": 0.5,
          "Gender": 1.0,
          "Nationality": 1.0,
          "Issuing_Country": 1.0,
          "MRZ": 1.0,
          "Date_Of_Issue": 1.0,
          "Date_Of_Expiry": 1.0,
          "Place_Of_Birth": 1.0,
          "Issuing_Authority": 1.0,
          "avg": 0.964
     },
     "False Positives": {
          "classification": 0.0,
          "Passport_Number": 1.0,
          "Passport_Type": 0.0,
          "Given_Name": 0.0,
          "Date_Of_Birth": 0.0,
          "Surname": 0.0,
          "Gender": 0.0,
          "Nationality": 0.0,
          "Issuing_Country": 0.0,
          "MRZ": 0.0,
          "Date_Of_Issue": 0.0,
          "Date_Of_Expiry": 0.0,
          "Place_Of_Birth": 0.0,
          "Issuing_Authority": 0.0,
          "avg": 0.071
     }
}